// <auto-generated />
using FastFoodManagementAPI.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastFoodManagementAPI.Migrations;
[DbContext(typeof(FastFoodDbContext))]
partial class FastFoodDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("FastFoodManagementAPI.Features.Orders.Order", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("OrderStatus")
                    .HasColumnType("int");

                b.Property<int?>("TableId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Orders");
            });

        modelBuilder.Entity("FastFoodManagementAPI.Features.Orders.OrderItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("OrderId")
                    .HasColumnType("int");

                b.Property<int>("ProductId")
                    .HasColumnType("int");

                b.Property<string>("ProductName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Quantity")
                    .HasColumnType("int");

                b.Property<decimal>("UnitPrice")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.HasIndex("OrderId");

                b.HasIndex("ProductId");

                b.ToTable("OrderItems");
            });

        modelBuilder.Entity("FastFoodManagementAPI.Features.Products.Product", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ImagePath")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("Stock")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .HasDatabaseName("IX_Product_Name");

                b.ToTable("Products");
            });

        modelBuilder.Entity("FastFoodManagementAPI.Features.Orders.OrderItem", b =>
            {
                b.HasOne("FastFoodManagementAPI.Features.Orders.Order", "Order")
                    .WithMany("OrderItems")
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("FastFoodManagementAPI.Features.Products.Product", "Product")
                    .WithMany("OrderItems")
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Order");

                b.Navigation("Product");
            });

        modelBuilder.Entity("FastFoodManagementAPI.Features.Orders.Order", b =>
            {
                b.Navigation("OrderItems");
            });

        modelBuilder.Entity("FastFoodManagementAPI.Features.Products.Product", b =>
            {
                b.Navigation("OrderItems");
            });
#pragma warning restore 612, 618
    }
}
