@FastFoodManagementAPI_HostAddress = https://localhost:7243


// Get all products
GET {{FastFoodManagementAPI_HostAddress}}/api/products

###



// Create order
POST {{FastFoodManagementAPI_HostAddress}}/api/orders
Content-Type: application/json

{
    "TableId": 99,
    "Items": [
      {
        "productId": 3,
        "quantity": 1
      }
    ]
}

###


// Get all orders
GET {{FastFoodManagementAPI_HostAddress}}/api/orders

###

// Update order status
PATCH {{FastFoodManagementAPI_HostAddress}}/api/orders/3
Content-Type: application/json

{
  "OrderStatus": "Paid"
}

###



// Get all orders by status
GET {{FastFoodManagementAPI_HostAddress}}/api/orders/status/Completed

###
